### ISSUE TITLE
Figures in README is not shown

### ISSUE THREAD

**Issue by zhanxw** [lch14forever/microbiomeViz#13]
The links to the figures are not long valid, e.g. ![](http://lchblogs.netlify.com/post/2018-01-18-r-metagenomeViz_files/figure-html/unnamed-chunk-4-1.png)

**Comment by zhanxw** [comment]
I can create a simple pull request to fix this, if needed.

I also wonder if this project will be maintained. 
If so, I hope to contribute codes. Thanks.

**Comment by lch14forever** [comment]
I have fixed the links.
You are more than welcome to contribute of course.

**Comment by zhanxw** [comment]
Thanks for the quick fix. 

I just created a pull request #14 and hope they can be incorporated.
