### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mmloine** [lch14forever/microbiomeViz#17]
Visualizator.r in the cloned source code contains one more character on 155 lines, causing the package installation to fail.

error line :facet_grid(group~., scale='free_y',  space = "free_y",

correct line:facet_grid(group~., scale='free_y', space = "free_y",
Idea reminds me that it is hard to distinguish with naked eyes

**Comment by lch14forever** [comment]
Thanks for reporting. I think this should be fixed in commit e22d7b1 .
