### ISSUE TITLE
The download method should be update_using the BiocManager

### ISSUE THREAD

**Issue by celine77** [lch14forever/microbiomeViz#19]
1. When i perform it : devtools::install_github("lch14forever/microbiomeViz")
The error is as follow: 

Downloading GitHub repo lch14forever/microbiomeViz@HEAD
Skipping 2 packages not available: treeio, ggtree
✓  checking for file ‘/private/var/folders/l4/lcqqh9s553vf2k5j0r3ybhjm0000gn/T/Rtmp65LL9h/remotes11d553b575199/lch14forever-microbiomeViz-e22d7b1/DESCRIPTION’ (362ms)
─  preparing ‘microbiomeViz’:
✓  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘microbiomeViz_0.1.0.tar.gz’
   
* installing *source* package ‘microbiomeViz’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error: object ‘get_aes_var’ is not exported by 'namespace:rvcheck'
Execution halted
ERROR: lazy loading failed for package ‘microbiomeViz’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/microbiomeViz’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/l4/lcqqh9s553vf2k5j0r3ybhjm0000gn/T//Rtmp65LL9h/file11d5561ae323e/microbiomeViz_0.1.0.tar.gz’ had non-zero exit status

-----------------
2. considering the Error: With R version 3.5 or greater, install Bioconductor packages using BiocManager; see https://bioconductor.org/install

The download method should be update as follows:

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("ggtree")
BiocManager::install("treeio")

I add the follow script but still did not work:

**Comment by lch14forever** [comment]
I think this is not related to this package. Most likely similar to this:
https://support.bioconductor.org/p/9139604/#9139615
