### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by 2533245542** [lch14forever/microbiomeViz#4]
I tried the example in Windows and it is not working. Here is the error message. I used the latest development version of treeio and ggtree. 

>data("SRS014459_Stool_profile")
> 
> tr <- parseMetaphlanTSV(SRS014459_Stool_profile)
Error in mutate_impl(.data, dots) : 
  Evaluation error: 'x' must be an array of at least two dimensions.

**Comment by lch14forever** [comment]
I have just reverted back to the previous commit. Please try again.

**Comment by 2533245542** [comment]
It is working now. Do you have plans putting this package to CRAN or Bioconductor?

**Comment by lch14forever** [comment]
That will be the ultimate goal. I am still trying to figure out a direction of this package. So far it just contains a parser for data produced by softwares like metaphlan. If you have any suggestions or feature requests, I am happy to put them onto my todo list.
