### ISSUE TITLE
add dependency to stringr

### ISSUE THREAD

**Issue by 2533245542** [lch14forever/microbiomeViz#8]
Hi, it is just a minor issue. When I use microbiomeviz for phyloseq object following the example, I got "Error in str_c(...)...." when doing "tr = parsePhyloseq(GP)". I believe it is due to stringr is not loaded when microbiomeviz is loaded, yet it did get installed when installing microbiomeviz. Just a minor issue and I think you are doing a great job in incorporating phyloseq object and .BIOM into your package!

**Comment by 2533245542** [comment]
By the way does phyloseq object support annotation? I might be wrong but when I tried doing annotation, it did not work.

**Comment by lch14forever** [comment]
Hi,

I personally had very bad experience with the phyloseq package dependency. I will give it a try but no guarantee to make it work.

**Comment by 2533245542** [comment]
Sure. I am trying to use GraPhlAn in one of my shiny app and it would be the best without interacting with Python. If there is anything I can help, be sure to let me know!

**Comment by lch14forever** [comment]
Closed for now
